### ISSUE TITLE
Update intro for March 24 workshop

### ISSUE THREAD

**Issue by samumantha** [coderefinery/workshop-intro#38]
Starting a collection , please help adding stuff:

- [x] add linked in link
- [x] make more compact, rather link to outro for all CR general stuff? -> aim for 15 min
- [x] "Why we are here" -> https://twitter.com/HeidiBaya/status/1579385587865649153?t=a-kbAMIFYAtdN1p2iZolJQ&s=19
- [x] mention that lesson material is more than what we go through here
- [x] add "create a folder for the workshop" to intro (maybe as part of checklist to get ready?)
- [ ] ...

**Comment by bast** [comment]
- don't advertise gitlab service
